name: dart_vlc_example
description: Demonstrates how to use the dart_vlc plugin.
publish_to: "none"

environment:
  sdk: ">=3.1.3 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  dart_vlc:
    path: ../

dependency_overrides:
  dart_vlc_ffi:
    path: ../ffi

  cupertino_icons: ^1.0.2
flutter:
  uses-material-design: true
