name: dart_vlc
description: Flutter audio / video playback, broadcast & recording library for Windows & Linux. Based on libvlc.
version: 0.4.0
homepage: https://github.com/alexmercerind/dart_vlc
repository: https://github.com/alexmercerind/dart_vlc
documentation: https://github.com/alexmercerind/dart_vlc/blob/master/README.md
publish_to: none

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.2
  dart_vlc_ffi: 
    path: ./ffi
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  lints: ^2.0.1

flutter:
  # No platform channel implementation after migration to FFI.
  plugin:
    platforms:
      windows:
        pluginClass: DartVlcPlugin
      linux:
        pluginClass: DartVlcPlugin
